<?php

/** Generated by Latte 3.1.6 */

use Latte\Runtime as LR;

/** source: /root/random.number/nette-blog/app/Presentation/@layout.latte */
final class Template_d444cb857fd6d0fe extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">

	<title>';
		if ($this->hasBlock('title')) /* pos 7:9 */ {
			$this->renderBlock('title', [], function ($s, $type) {
				$ʟ_fi = new LR\FilterInfo($type);
				return LR\Helpers::convertTo($ʟ_fi, 'html', $this->filters->filterContent('stripHtml', $ʟ_fi, $s));
			}) /* pos 7:22 */;
			echo ' | ';
		}
		echo 'Nette Web</title>

	';
		if ($ʟ_tmp = $this->global->assets->resolve('main.js', [], true)) /* pos 9:2 */ {
			echo $this->global->assets->renderAsset($ʟ_tmp);
		}echo '
</head>

<body>
';
		foreach ($flashes as $flash) /* pos 13:7 */ {
			echo '	<div';
			echo ($ʟ_tmp = array_filter(['flash', $flash->type])) ? ' class="' . LR\HtmlHelpers::escapeAttr(implode(" ", array_unique($ʟ_tmp))) . '"' : "" /* pos 13:38 */;
			echo '>';
			echo LR\HtmlHelpers::escapeText($flash->message) /* pos 13:68 */;
			echo '</div>
';

		}

		echo "\n";
		$this->renderBlock('content', [], 'html') /* pos 15:2 */;
		echo '</body>
</html>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['flash' => '13'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
