<?php

/** Generated by Latte 3.1.6 */

use Latte\Runtime as LR;

/** source: /root/random.number/nette-blog/app/Presentation/Home/default.latte */
final class Template_2125b0e3405a5a37 extends Latte\Runtime\Template
{
	public const Blocks = [
		0 => ['content' => 'blockContent', 'title' => 'blockTitle'],
		'snippet' => ['pleaseReload' => 'blockPleaseReload'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* pos 1:1 */;
	}


	/** {block content} on line 1 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('title', get_defined_vars()) /* pos 3:5 */;
		echo "\n";
		echo '<div id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('pleaseReload')), '">';
		$this->renderBlock('pleaseReload', [], null, 'snippet') /* pos 5:1 */;
		echo '</div>

<a href="';
		echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link('generateRandomNumber!')) /* pos 10:4 */;
		echo '" class="ajax">Generuj Ajaxově!</a>
';
	}


	/** n:block="title" on line 3 */
	public function blockTitle(array $ʟ_args): void
	{
		echo '<h1>Welcome to Nette Framework!</h1>
';
	}


	/** {snippet pleaseReload} on line 5 */
	public function blockPleaseReload(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter('pleaseReload', 'static') /* pos 5:1 */;
		try {
			echo "\n";
			$randomNumber = rand(1, 100) /* pos 6:2 */;
			echo '	<p>Your random number is: ';
			echo LR\HtmlHelpers::escapeText($randomNumber) /* pos 7:28 */;
			echo '</p>
';

		} finally {
			$this->global->snippetDriver->leave();
		}
	}
}
